version: "3.8"

services:
  influxdb_raw:
    image: influxdb:2.7
    container_name: influxdb_raw
    restart: always
    ports:
      - "8087:8086"
    env_file:
      - .env
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - INFLUXDB_INIT_BUCKET=raw_data
      - INFLUXDB_INIT_RETENTION=0
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb2-raw-data:/var/lib/influxdb2
      - influxdb2-raw-config:/etc/influxdb2

  influxdb_processed:
    image: influxdb:2.7
    container_name: influxdb_processed
    restart: always
    ports:
      - "8086:8086"  # Different port
    env_file:
      - .env
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - INFLUXDB_INIT_BUCKET=processed_data
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB2_TOKEN}
    volumes:
      - influxdb2-processed-data:/var/lib/influxdb2
      - influxdb2-processed-config:/etc/influxdb2

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "${CLICKHOUSE_PORT_HTTP}"
      - "${CLICKHOUSE_PORT_NATIVE}"
    env_file:
      - .env
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  data_ingest:
    build: .
    container_name: data_ingest
    restart: on-failure
    depends_on:
      - influxdb_raw
    environment:
      - INFLUXDB_URL=http://influxdb_raw:8087
    volumes:
      - ./ground_truth_insert.py:/app/ground_truth_insert.py
      - ./NUSW-NB15_GT.csv:/app/NUSW-NB15_GT.csv
    command: ["python", "/app/ground_truth_insert.py"]

volumes:
  influxdb2-raw-data:
  influxdb2-raw-config:
  influxdb2-processed-data:
  influxdb2-processed-config:
  clickhouse_data:
  chronograf_data:
