version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_INIT_RETENTION=0
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb2-data:/var/lib/influxdb2  # Store database data
      - influxdb2-config:/etc/influxdb2    # Store configuration

volumes:
  influxdb2-data:
  influxdb2-config:
