FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./src/ndap/data_storage/raw_data_storer.py /app

CMD ["python", "raw_data_storer.py"]