FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY NUSW-NB15_GT.csv /app/NUSW-NB15_GT.csv
RUN pip install -r /app/requirements.txt

COPY . .

CMD ["python", "/app/ground_truth_insert.py"]
