version: "3.8"
name: ndap

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.2
    ports:
      - "9009:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092" # Kafka Broker Network Addresses (host:port,host:port)
      SERVER_SERVLET_CONTEXTPATH: "/"

  nwdaf_collector:
    build: 
      context: .
      dockerfile: ./src/ndap/data_producer/Dockerfile
    container_name: nwdaf_collector
    restart: always
    ports:
      - "8071:8071"  # host:container
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./dataset_files:/app/dataset_files
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  nrf:
    build:
      context: .
      dockerfile: ./src/ndap/NRF_API/Dockerfile
    container_name: nrf
    restart: always
    ports:
      - "8070:8070"  # host:container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  data_relay:
    build: 
      context: .
      dockerfile: ./src/ndap/data_relay/Dockerfile
    container_name: data_relay
    restart: always
    ports:
      - "8073:8073"  # host:container
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8073/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  influxdb_raw:
    image: influxdb:2.7
    container_name: influxdb_raw
    restart: always
    ports:
      - "8087:8086"
    env_file:
      - .env
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - INFLUXDB_INIT_BUCKET=raw_data
      - INFLUXDB_INIT_RETENTION=0
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb2-raw-data:/var/lib/influxdb2
      - influxdb2-raw-config:/etc/influxdb2

  influxdb_processed:
    image: influxdb:2.7
    container_name: influxdb_processed
    restart: always
    ports:
      - "8086:8086"  # Different port
    env_file:
      - .env
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - INFLUXDB_INIT_BUCKET=processed_data
      - INFLUXDB_INIT_RETENTION=0
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB2_TOKEN}
    volumes:
      - influxdb2-processed-data:/var/lib/influxdb2
      - influxdb2-processed-config:/etc/influxdb2

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "${CLICKHOUSE_PORT_HTTP}"
      - "${CLICKHOUSE_PORT_NATIVE}"
    env_file:
      - .env
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./src/ndap/data_storage/init_clickhouse.sql:/docker-entrypoint-initdb.d/init.sql

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - influxdb_processed
    command: >
      chronograf
      --influxdb-url=http://influxdb_processed:8086/
      --influxdb-org=${INFLUXDB2_ORG}
      --influxdb-token=${INFLUXDB2_TOKEN}
    environment:
      - BOLT_PATH=/var/lib/chronograf/chronograf-v1.db
    volumes:
      - chronograf_data:/var/lib/chronograf/

  data_storage_middleware:
    build:
      context: .
      dockerfile: ./src/ndap/data_storage/Dockerfile.storage_middleware
    container_name: data_storage_middleware
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

  data_raw_storer:
    build: 
      context: .
      dockerfile: ./src/ndap/data_storage/Dockerfile.dbraw
    container_name: data_raw_storer
    restart: always
    depends_on:
      influxdb_raw:
        condition: service_started
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - INFLUXDB_URL=http://influxdb_raw:8087
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - ./logs:/app/logs
  
  data_raw_extractor:
    build: 
      context: .
      dockerfile: ./src/ndap/data_storage/Dockerfile.extractor
    container_name: data_raw_extractor
    restart: always
    depends_on:
      influxdb_raw:
        condition: service_started
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - INFLUXDB_URL=http://influxdb_raw:8087
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - ./logs:/app/logs

  data_consumer:
    build: 
      context: .
      dockerfile: ./src/ndap/dashboard_interface/Dockerfile
    container_name: data_consumer
    restart: always
    ports:
      - "8074:8074"  # host:container
    depends_on:
      influxdb_processed:
        condition: service_started
      data_relay:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - INFLUXDB2_ORG=${INFLUXDB2_ORG}
      - INFLUXDB2_TOKEN=${INFLUXDB2_TOKEN}
    volumes:
      - ./logs:/app/logs

  data_processor:
    build: 
      context: .
      dockerfile: ./src/ndap/data_processor/Dockerfile
    container_name: data_processor
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    
  data_receiver:
    build: 
      context: .
      dockerfile: ./src/ndap/data_receiver/Dockerfile
    container_name: data_receiver
    restart: always
    ports:
      - "8072:8072"  # host:container
    depends_on:
      kafka:
        condition: service_healthy
      nrf:
        condition: service_healthy
      nwdaf_collector:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

volumes:
  influxdb2-raw-data:
  influxdb2-raw-config:
  influxdb2-processed-data:
  influxdb2-processed-config:
  clickhouse_data:
  chronograf_data: